### ISSUE TITLE
filter button color should change to white when on.

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/kj-frontend#15]
According to current implementation, when we click filter button thus far it opens the filter options, but it's color remains same dark grey. It would be great if we can change it's color to white while selected.

**Comment by saurabh9887** [comment]
Hi bro, I want to contribute to this issue but I have never worked on the next js before. I can solve the issue but I am facing some problems with the next js, can you please help me with that?

**Comment by parneetsingh022** [comment]
What problems are you facing, feel free to ask me.

**Comment by parneetsingh022** [comment]
> Hi bro, I want to contribute to this issue but I have never worked on the next js before. I can solve the issue but I am facing some problems with the next js, can you please help me with that?

What problems are you facing? Feel free to ask me.

**Comment by saurabh9887** [comment]
While building simple websites and also while working with React js we first create index.html from where we start our progress in building a website so I am unable to find such file. Also, the bash command you provided in the readme file is not working on my local machine

**Comment by parneetsingh022** [comment]
React and Nextjs do not have index.html file but rather index.js file. Html is directly stored in javascript file.

In next js pages are stored in pages directory, so you will find index.js there. This is because in next js we do not have to create routes but individual page (js file) in pages directory serves as a route.

Other components which have been used are stored in components directory and the file concerned with this issue is search_filters.js in components folder.

Secondly, in order to run the bash command you have to install node.js and then yarn itself. You can find plenty of YouTube tutorials on installing nodejs and yarn.

**Comment by saurabh9887** [comment]
I am seeing this error while running bash yarn dev
![Screenshot (15)](https://user-images.githubusercontent.com/101647540/233855090-0f853ffc-2333-4378-a37d-9135467a30e1.png)

**Comment by okhuaroboosayuki** [comment]
> I am seeing this error while running bash yarn dev ![Screenshot (15)](https://user-images.githubusercontent.com/101647540/233855090-0f853ffc-2333-4378-a37d-9135467a30e1.png)

bash is a CLI itself; "yarn dev" is the appropriate command

**Comment by saurabh190802** [comment]
@parneetsingh022 I have fixed this. opening a PR, Kindly check.

https://user-images.githubusercontent.com/75023861/233860424-c0bc85eb-49ef-45cb-8d79-aa428c730b10.mp4

**Comment by parneetsingh022** [comment]
Hi @saurabh190802
Thank you and I will review it.
