### ISSUE TITLE
Search filter toggle not using colors from globals.css

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/kj-frontend#18]
@saurabh190802 fixed the issue #15 and is working great. But there is a potential problem which it could lead to in future.

It is using colors 'grey' and 'white' which were defined on following line (in `components/search_filters.js`):
```javascript 
setfilterButtonColor((prev) => (prev === "white" ? "grey" : "white"));
```
It is important to use colors from globals.css rather than writing them like that. 
For grey toggle color we can use ```---foreground1``` and for white toggle ```--foreground2```

**Comment by saurabh190802** [comment]
> @saurabh190802 fixed the issue #15 and is working great. But there is a potential problem which it could lead to in future.
> 
> It is using colors 'grey' and 'white' which were defined on following line (in `components/search_filters.js`):
> ```javascript 
> setfilterButtonColor((prev) => (prev === "white" ? "grey" : "white"));
> ```
> It is important to use colors from globals.css rather than writing them like that. 
> For grey toggle color we can use ```---foreground1``` and for white toggle ```--foreground2```

Okay I'm changing this

**Comment by saurabh190802** [comment]
@parneetsingh022  fixed. opening a pr kindly check 
![image](https://user-images.githubusercontent.com/75023861/233901337-57c4df1a-8c27-4beb-8ac5-20ae55c08d97.png)

**Comment by parneetsingh022** [comment]
Ok I'll check it.

**Comment by parneetsingh022** [comment]
@saurabh190802 
Great! this fixes the issue and PR is merged successfully.

**Comment by saurabh190802** [comment]
> @saurabh190802 Great! this fixes the issue and PR is merged successfully.

Thanks @parneetsingh022
