### ISSUE TITLE
Need to add animation on filter box.

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/kj-frontend#21]
After clicking on filter toggle the filter box opens suddenly. It would be great if we could implement sliding down animation to it when toggle filter button is clicked.

![Capture](https://user-images.githubusercontent.com/99793808/233916776-877b8fd5-48bd-4200-a975-f981641e929b.JPG)

**Comment by dz-ai** [comment]
I would like to go for it

**Comment by parneetsingh022** [comment]
@dz-ai sure
