### ISSUE TITLE
Side navbar's blurry background won't go away if we make the screen bigger without closing it!

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/kj-frontend#22]
If we open the sidebar in small screen and make the screen bigger without closing it the background still remains blurry!!!

How to reproduce this issue:
-make the width of window small until menu bar appears.
-click the menu bar.
-without closing it make the window large.
-you won't be able to click on any link or anywhere because of the blurry background of the navbar.

**Comment by RohanJacob23** [comment]
Hello @parneetsingh022,

I noticed the bug and have worked on it. I have created a pull request, could you please review it?

**Comment by parneetsingh022** [comment]
@RohanJacob23 
Seems to have been fixed.
