### ISSUE TITLE
Responsive navbar style should be changed.

### ISSUE THREAD

**Issue by parneetsingh022** [parneetsingh022/kj-frontend#9]
Current implementation of navbar uses flex-direction:column. Though it is ok for current implementation thus far but **It would be great if we could do a navbar with a menu icon for small devices**.

![Capture](https://user-images.githubusercontent.com/99793808/233769995-0ea264da-d489-4910-8864-6487408e1145.JPG)

**Comment by RohanJacob23** [comment]
Hi @parneetsingh022,

I would like to contribute to this project.

Is it okay if I use a UI framework for the menu, or do you need me to create it from pure CSS and HTML?

**Comment by parneetsingh022** [comment]
@RohanJacob23 
I would prefer you to use the original design (css) I've written and create upon that instead of using UI framework.

**Comment by RohanJacob23** [comment]
Okay, I will work on it.

**Comment by RohanJacob23** [comment]
Hello @parneetsingh022,

I have created a PR, could you please review it.

**Comment by parneetsingh022** [comment]
Hi @RohanJacob23 
I've reviewed your PR and there are some fixes needed to be done.
Kindly Check
